# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ASFWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ASFWidget(object):
    def setupUi(self, ASFWidget):
        ASFWidget.setObjectName("ASFWidget")
        ASFWidget.resize(400, 400)
        ASFWidget.setMinimumSize(QtCore.QSize(400, 400))
        ASFWidget.setMaximumSize(QtCore.QSize(400, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(ASFWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(ASFWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(ASFWidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 70))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 70))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(ASFWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(ASFWidget)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout.addWidget(self.lineEdit_1, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(ASFWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(ASFWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(ASFWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(ASFWidget)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(ASFWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(ASFWidget)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(ASFWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(ASFWidget)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(ASFWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(ASFWidget)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(ASFWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(ASFWidget)
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(ASFWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(ASFWidget)
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(ASFWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(ASFWidget)
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 4, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(ASFWidget)
        QtCore.QMetaObject.connectSlotsByName(ASFWidget)

    def retranslateUi(self, ASFWidget):
        _translate = QtCore.QCoreApplication.translate
        ASFWidget.setWindowTitle(_translate("ASFWidget", "Form"))
        self.label.setText(_translate("ASFWidget", "LUT1/H"))
        self.label_2.setText(_translate("ASFWidget", "shapL:0-3"))
        self.label_3.setText(_translate("ASFWidget", "reg_hh"))
        self.label_7.setText(_translate("ASFWidget", "smax"))
        self.label_4.setText(_translate("ASFWidget", "reg_hl"))
        self.label_8.setText(_translate("ASFWidget", "omax"))
        self.label_5.setText(_translate("ASFWidget", "reg_vh"))
        self.label_9.setText(_translate("ASFWidget", "smin"))
        self.label_6.setText(_translate("ASFWidget", "oreg_vlmin"))
        self.label_10.setText(_translate("ASFWidget", "omin"))

