# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GammaWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GammaWidget(object):
    def setupUi(self, GammaWidget):
        GammaWidget.setObjectName("GammaWidget")
        GammaWidget.resize(520, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GammaWidget.sizePolicy().hasHeightForWidth())
        GammaWidget.setSizePolicy(sizePolicy)
        GammaWidget.setMinimumSize(QtCore.QSize(520, 700))
        GammaWidget.setMaximumSize(QtCore.QSize(520, 700))
        self.layoutWidget = QtWidgets.QWidget(GammaWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 1, 514, 685))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(512, 512))
        self.label.setMaximumSize(QtCore.QSize(512, 512))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(512, 50))
        self.groupBox.setMaximumSize(QtCore.QSize(512, 60))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rbCamera0 = QtWidgets.QRadioButton(self.groupBox)
        self.rbCamera0.setChecked(True)
        self.rbCamera0.setObjectName("rbCamera0")
        self.horizontalLayout_4.addWidget(self.rbCamera0)
        self.rbCamera1 = QtWidgets.QRadioButton(self.groupBox)
        self.rbCamera1.setObjectName("rbCamera1")
        self.horizontalLayout_4.addWidget(self.rbCamera1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(512, 50))
        self.groupBox_2.setMaximumSize(QtCore.QSize(512, 60))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rbBright = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbBright.setObjectName("rbBright")
        self.horizontalLayout_5.addWidget(self.rbBright)
        self.rbNormal = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbNormal.setChecked(True)
        self.rbNormal.setObjectName("rbNormal")
        self.horizontalLayout_5.addWidget(self.rbNormal)
        self.rbLow = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbLow.setChecked(False)
        self.rbLow.setObjectName("rbLow")
        self.horizontalLayout_5.addWidget(self.rbLow)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(GammaWidget)
        self.pushButton.clicked.connect(GammaWidget.PushGAMMA)
        self.pushButton_2.clicked.connect(GammaWidget.PullGAMMA)
        self.rbBright.clicked.connect(GammaWidget.BrightClicked)
        self.rbNormal.clicked.connect(GammaWidget.NormalClicked)
        self.rbLow.clicked.connect(GammaWidget.LowClicked)
        QtCore.QMetaObject.connectSlotsByName(GammaWidget)

    def retranslateUi(self, GammaWidget):
        _translate = QtCore.QCoreApplication.translate
        GammaWidget.setWindowTitle(_translate("GammaWidget", "Form"))
        self.groupBox.setTitle(_translate("GammaWidget", "Camera"))
        self.rbCamera0.setText(_translate("GammaWidget", "Camera0"))
        self.rbCamera1.setText(_translate("GammaWidget", "Camera1"))
        self.groupBox_2.setTitle(_translate("GammaWidget", "Gamma"))
        self.rbBright.setText(_translate("GammaWidget", "Bright"))
        self.rbNormal.setText(_translate("GammaWidget", "Normal"))
        self.rbLow.setText(_translate("GammaWidget", "Low"))
        self.label_2.setText(_translate("GammaWidget", "Type and Ratio:"))
        self.pushButton_2.setText(_translate("GammaWidget", "PullGAMMA"))
        self.pushButton.setText(_translate("GammaWidget", "PushGAMMA"))

