# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WNRWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WNRWidget(object):
    def setupUi(self, WNRWidget):
        WNRWidget.setObjectName("WNRWidget")
        WNRWidget.resize(512, 512)
        WNRWidget.setMinimumSize(QtCore.QSize(512, 512))
        WNRWidget.setMaximumSize(QtCore.QSize(512, 512))
        self.verticalLayout = QtWidgets.QVBoxLayout(WNRWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(WNRWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.NoiseProfile = QtWidgets.QTextBrowser(WNRWidget)
        self.NoiseProfile.setMinimumSize(QtCore.QSize(0, 70))
        self.NoiseProfile.setMaximumSize(QtCore.QSize(16777215, 70))
        self.NoiseProfile.setReadOnly(False)
        self.NoiseProfile.setObjectName("NoiseProfile")
        self.verticalLayout.addWidget(self.NoiseProfile)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.EdgeS_Y0 = QtWidgets.QLineEdit(WNRWidget)
        self.EdgeS_Y0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EdgeS_Y0.setObjectName("EdgeS_Y0")
        self.gridLayout.addWidget(self.EdgeS_Y0, 2, 1, 1, 1)
        self.EdgeS_Y1 = QtWidgets.QLineEdit(WNRWidget)
        self.EdgeS_Y1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EdgeS_Y1.setObjectName("EdgeS_Y1")
        self.gridLayout.addWidget(self.EdgeS_Y1, 2, 2, 1, 1)
        self.Scale_Y0 = QtWidgets.QLineEdit(WNRWidget)
        self.Scale_Y0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Scale_Y0.setObjectName("Scale_Y0")
        self.gridLayout.addWidget(self.Scale_Y0, 0, 1, 1, 1)
        self.Weight_Y3 = QtWidgets.QLineEdit(WNRWidget)
        self.Weight_Y3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Weight_Y3.setObjectName("Weight_Y3")
        self.gridLayout.addWidget(self.Weight_Y3, 4, 4, 1, 1)
        self.Weight_Chroma1 = QtWidgets.QLineEdit(WNRWidget)
        self.Weight_Chroma1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Weight_Chroma1.setObjectName("Weight_Chroma1")
        self.gridLayout.addWidget(self.Weight_Chroma1, 5, 2, 1, 1)
        self.EdgeS_Y2 = QtWidgets.QLineEdit(WNRWidget)
        self.EdgeS_Y2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EdgeS_Y2.setObjectName("EdgeS_Y2")
        self.gridLayout.addWidget(self.EdgeS_Y2, 2, 3, 1, 1)
        self.Scale_Y1 = QtWidgets.QLineEdit(WNRWidget)
        self.Scale_Y1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Scale_Y1.setObjectName("Scale_Y1")
        self.gridLayout.addWidget(self.Scale_Y1, 0, 2, 1, 1)
        self.Scale_Chroam0 = QtWidgets.QLineEdit(WNRWidget)
        self.Scale_Chroam0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Scale_Chroam0.setObjectName("Scale_Chroam0")
        self.gridLayout.addWidget(self.Scale_Chroam0, 1, 1, 1, 1)
        self.EdgeS_Chroma1 = QtWidgets.QLineEdit(WNRWidget)
        self.EdgeS_Chroma1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EdgeS_Chroma1.setObjectName("EdgeS_Chroma1")
        self.gridLayout.addWidget(self.EdgeS_Chroma1, 3, 2, 1, 1)
        self.Scale_Chroam2 = QtWidgets.QLineEdit(WNRWidget)
        self.Scale_Chroam2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Scale_Chroam2.setObjectName("Scale_Chroam2")
        self.gridLayout.addWidget(self.Scale_Chroam2, 1, 3, 1, 1)
        self.Scale_Y3 = QtWidgets.QLineEdit(WNRWidget)
        self.Scale_Y3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Scale_Y3.setObjectName("Scale_Y3")
        self.gridLayout.addWidget(self.Scale_Y3, 0, 4, 1, 1)
        self.Scale_Chroam3 = QtWidgets.QLineEdit(WNRWidget)
        self.Scale_Chroam3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Scale_Chroam3.setObjectName("Scale_Chroam3")
        self.gridLayout.addWidget(self.Scale_Chroam3, 1, 4, 1, 1)
        self.Weight_Chroma3 = QtWidgets.QLineEdit(WNRWidget)
        self.Weight_Chroma3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Weight_Chroma3.setObjectName("Weight_Chroma3")
        self.gridLayout.addWidget(self.Weight_Chroma3, 5, 4, 1, 1)
        self.Scale_Chroam1 = QtWidgets.QLineEdit(WNRWidget)
        self.Scale_Chroam1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Scale_Chroam1.setObjectName("Scale_Chroam1")
        self.gridLayout.addWidget(self.Scale_Chroam1, 1, 2, 1, 1)
        self.EdgeS_Chroma2 = QtWidgets.QLineEdit(WNRWidget)
        self.EdgeS_Chroma2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EdgeS_Chroma2.setObjectName("EdgeS_Chroma2")
        self.gridLayout.addWidget(self.EdgeS_Chroma2, 3, 3, 1, 1)
        self.Weight_Y1 = QtWidgets.QLineEdit(WNRWidget)
        self.Weight_Y1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Weight_Y1.setObjectName("Weight_Y1")
        self.gridLayout.addWidget(self.Weight_Y1, 4, 2, 1, 1)
        self.Weight_Y2 = QtWidgets.QLineEdit(WNRWidget)
        self.Weight_Y2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Weight_Y2.setObjectName("Weight_Y2")
        self.gridLayout.addWidget(self.Weight_Y2, 4, 3, 1, 1)
        self.Weight_Chroma0 = QtWidgets.QLineEdit(WNRWidget)
        self.Weight_Chroma0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Weight_Chroma0.setObjectName("Weight_Chroma0")
        self.gridLayout.addWidget(self.Weight_Chroma0, 5, 1, 1, 1)
        self.EdgeS_Y3 = QtWidgets.QLineEdit(WNRWidget)
        self.EdgeS_Y3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EdgeS_Y3.setObjectName("EdgeS_Y3")
        self.gridLayout.addWidget(self.EdgeS_Y3, 2, 4, 1, 1)
        self.Scale_Y2 = QtWidgets.QLineEdit(WNRWidget)
        self.Scale_Y2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Scale_Y2.setObjectName("Scale_Y2")
        self.gridLayout.addWidget(self.Scale_Y2, 0, 3, 1, 1)
        self.Weight_Y0 = QtWidgets.QLineEdit(WNRWidget)
        self.Weight_Y0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Weight_Y0.setObjectName("Weight_Y0")
        self.gridLayout.addWidget(self.Weight_Y0, 4, 1, 1, 1)
        self.EdgeS_Chroma3 = QtWidgets.QLineEdit(WNRWidget)
        self.EdgeS_Chroma3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EdgeS_Chroma3.setObjectName("EdgeS_Chroma3")
        self.gridLayout.addWidget(self.EdgeS_Chroma3, 3, 4, 1, 1)
        self.EdgeS_Chroma0 = QtWidgets.QLineEdit(WNRWidget)
        self.EdgeS_Chroma0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.EdgeS_Chroma0.setObjectName("EdgeS_Chroma0")
        self.gridLayout.addWidget(self.EdgeS_Chroma0, 3, 1, 1, 1)
        self.Weight_Chroma2 = QtWidgets.QLineEdit(WNRWidget)
        self.Weight_Chroma2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Weight_Chroma2.setObjectName("Weight_Chroma2")
        self.gridLayout.addWidget(self.Weight_Chroma2, 5, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(WNRWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(WNRWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(WNRWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(WNRWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(WNRWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(WNRWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnPullWNR = QtWidgets.QPushButton(WNRWidget)
        self.btnPullWNR.setObjectName("btnPullWNR")
        self.horizontalLayout.addWidget(self.btnPullWNR)
        self.btnPushWNR = QtWidgets.QPushButton(WNRWidget)
        self.btnPushWNR.setObjectName("btnPushWNR")
        self.horizontalLayout.addWidget(self.btnPushWNR)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(WNRWidget)
        self.btnPushWNR.clicked.connect(WNRWidget.PushWNR)
        self.btnPullWNR.clicked.connect(WNRWidget.PullWNR)
        QtCore.QMetaObject.connectSlotsByName(WNRWidget)

    def retranslateUi(self, WNRWidget):
        _translate = QtCore.QCoreApplication.translate
        WNRWidget.setWindowTitle(_translate("WNRWidget", "Form"))
        self.label_2.setText(_translate("WNRWidget", "NoiseProfile"))
        self.label_8.setText(_translate("WNRWidget", "Weight_Chroma"))
        self.label_7.setText(_translate("WNRWidget", "Weight_Y"))
        self.label_6.setText(_translate("WNRWidget", "EdgeS_Chroma"))
        self.label_5.setText(_translate("WNRWidget", "EdgeS_Y"))
        self.label_4.setText(_translate("WNRWidget", "Scale_Chroam"))
        self.label_3.setText(_translate("WNRWidget", "Scale_Y"))
        self.btnPullWNR.setText(_translate("WNRWidget", "PullWNR"))
        self.btnPushWNR.setText(_translate("WNRWidget", "PushWNR"))

